I have got a bug since yesterday,  it is okay fixed just before one hour;
"type Rapport d''exception: message java.lang.NullPointerException

description Le serveur a rencontré une erreur interne qui l''a empêché de satisfaire la requête.

exception

javax.servlet.ServletException: java.lang.NullPointerException
	com.vaadin.terminal.gwt.server.AbstractApplicationServlet.handleServiceException(AbstractApplicationServlet.java:1010)
	com.vaadin.terminal.gwt.server.AbstractApplicationServlet.service(AbstractApplicationServlet.java:548)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:722)

cause mère

java.lang.NullPointerException
	nasreldin_johannes.MyVaadinApplication.buildMainLayout(MyVaadinApplication.java:59)
	nasreldin_johannes.MyVaadinApplication.init(MyVaadinApplication.java:55)
	com.vaadin.Application.start(Application.java:551)
	com.vaadin.terminal.gwt.server.AbstractApplicationServlet.startApplication(AbstractApplicationServlet.java:1219)
	com.vaadin.terminal.gwt.server.AbstractApplicationServlet.service(AbstractApplicationServlet.java:484)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:722)"

 I just fix it and restart to re-arrange